### ISSUE TITLE
Remove PGPy from the dependency list.

### ISSUE THREAD

**Issue by Cellebyte** [Selfnet/multivault#18]

**Comment by Hasimir** [comment]
Having now looked at PGPy's innards, this is an admirable aim for your project.  Just a quick FYI, though, some of the work-arounds for other things included with the [GPGME Python Bindings HOWTO](http ://files.au.adversary.org/crypto/gpgme-python-howto/webhelp/index.html) will result in subprocess returning.

Its use is minimised and never goes anywhere near actual cryptographic functions, but it is there in a couple of places, mainly running `gpgconf` or `gpgme-config`.  It is also only called using `subprocess.getoutput` and never using `subprocess.Popen` or `subprocess.call`, no shells are invoked and no user provided data is fed into it either (it's mainly used to determine the homedir and to grab existing config in `gpg.conf`) .
